name: dart_by_example
description: Examples that teach the use of Dart through short, directed code snippets.
dependencies:
  angular: 0.9.3
  crypto: any
  http: any
  http_server: any
  route: any
  unittest: any
